/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}', './lib/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        void: 'var(--void)',
        'surface-0': 'var(--surface-0)',
        'surface-1': 'var(--surface-1)',
        'surface-2': 'var(--surface-2)',
        'surface-3': 'var(--surface-3)',
        'text-bright': 'var(--text-bright)',
        'text-normal': 'var(--text-normal)',
        'text-dim': 'var(--text-dim)',
        'text-code': 'var(--text-code)',
        accent: 'var(--accent)',
        'accent-glow': 'var(--accent-glow)',
        'accent-dim': 'var(--accent-dim)',
        critical: 'var(--critical)',
        'critical-glow': 'var(--critical-glow)',
        high: 'var(--high)',
        'high-glow': 'var(--high-glow)',
        medium: 'var(--medium)',
        'medium-glow': 'var(--medium-glow)',
        safe: 'var(--low)',
        'safe-glow': 'var(--low-glow)',
        info: 'var(--info)',
        'info-glow': 'var(--info-glow)',
      },
      fontFamily: {
        sans: ['var(--font-geist-sans)', 'system-ui', 'sans-serif'],
        mono: ['var(--font-geist-mono)', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      borderRadius: {
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '20px',
        '3xl': '24px',
      },
      transitionDuration: {
        80: '80ms',
        150: '150ms',
        200: '200ms',
        250: '250ms',
      },
      boxShadow: {
        glow: '0 0 20px rgba(0, 212, 255, 0.1)',
        'glow-lg': '0 0 40px rgba(0, 212, 255, 0.15)',
        'glow-critical': '0 0 20px rgba(255, 51, 102, 0.15)',
        'glow-high': '0 0 20px rgba(255, 140, 66, 0.15)',
        card: '0 4px 24px rgba(0, 0, 0, 0.4)',
        'card-hover': '0 8px 40px rgba(0, 0, 0, 0.5)',
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
      },
    },
  },
  plugins: [],
}
